#!/bin/bash
#add for chkconfig
#chkconfig:23456 70 30
#description: frontend-service auto start

# # 变量读取
# var -- FrontEndDir
for var in `cat /etc/frontend`; do
  a=`echo $var | awk -F '=' '{print $1}'`
  b=`echo $var | awk -F '=' '{print $2}'`
  export $a=$b
done

# # Function

# 停止pm2进程
stop() {
  for pnumber in `pgrep PM2`
  do
    kill -3 $pnumber
  done
}

# 重启pm2进程
start() {
  cd $FrontEndDir
  bash pm2.$1.sh
}

# # Main Action
case $1 in

  start )
    start 'prod'
  ;;

  stop )
    stop
  ;;

  startDev )
    start 'dev'
  ;;

esac
