#!/bin/bash
#add for chkconfig
#chkconfig:23456 70 30
#description: frontend-service auto start

# # Function

# 停止pm2进程
stop() {
  for pnumber in `pgrep PM2`
  do
    kill -3 $pnumber
  done
}

# 重启pm2进程
start() {
  cd /opt/infinity/node-express-react
  bash pm2.$1.sh
}

# # MAIN
case $1 in

  start )
    start 'prod'
  ;;

  stop )
    stop
  ;;

  startDev )
    start 'dev'
  ;;

esac
