const patterns = {
  'CODE_SUCCESS': 200,
  'CODE_EXCPTION': 300,
  'CODE_ERROR': 400,

  'SMARTOR_SERVER': 'http://127.0.0.1/api',   // smartor服务
  'INFINITY_SERVER': 'http://127.0.0.1/api/infinity-v2',

  'IDENTIFY_CENTER_URL': SMARTOR_SERVER + '/identify',
  'CLUSTER_TRACKER_URL': SMARTOR_SERVER + '/cluster/tracker',
  'SMARTOR_STORAGE_DIR': SMARTOR_SERVER + '/storage/dir',
  'SMARTOR_STORAGE_VOLUME': SMARTOR_SERVER + '/storage/volume',
  'SMARTOR_STORAGE_AFP': SMARTOR_SERVER + '/storage/afp',
  'SMARTOR_STORAGE_FTP': SMARTOR_SERVER + '/storage/ftp',
  'SMARTOR_STORAGE_HTTP': SMARTOR_SERVER + '/storage/http',
  'SMARTOR_STORAGE_NFS': SMARTOR_SERVER + '/storage/nfs',
  'SMARTOR_STORAGE_CIFS': SMARTOR_SERVER + '/storage/cifs',

  'SMARTOR_USER_IDENTIFY': SMARTOR_SERVER + '/identify/user',
  'SMARTOR_GROUP_IDENTIFY': SMARTOR_SERVER + '/identify/group',
  'SMARTOR_AD_DOMAIN_IDENTIFY': SMARTOR_SERVER + '/system/user/ad',
  'SMARTOR_LDAP_DOMAIN_IDENTIFY': SMARTOR_SERVER + '/system/ldap',
  // user model 用户模块
  'INFINITY_USER_LIST': SMARTOR_USER_IDENTIFY + '/list',
  'INFINITY_USER_LOGIN': SMARTOR_USER_IDENTIFY + '/login',
  'INFINITY_USER_LOGOUT': SMARTOR_USER_IDENTIFY + '/logout',
  'INFINITY_USER_CREATE': SMARTOR_USER_IDENTIFY + '/create',
  'INFINITY_USER_REMOVE': SMARTOR_USER_IDENTIFY + '/remove',
  'INFINITY_USER_MODIFY': SMARTOR_USER_IDENTIFY + '/modify',
  'INFINITY_USER_MODIFYPWD': SMARTOR_USER_IDENTIFY + '/editpwd',
  'INFINITY_USER_RESETPWD': SMARTOR_USER_IDENTIFY + '/resetpwd',
  'SMARTOR_USER_LISTBYGROUP': SMARTOR_USER_IDENTIFY + '/listbygroup',
  'SMARTOR_USER_SEARCH': SMARTOR_USER_IDENTIFY + '/search',
  'INFINITY_USER_INFO': SMARTOR_USER_IDENTIFY + '/info',
  'INFINITY_OBJUSER': INFINITY_SERVER + '/os/user',
  'INFINITY_OBJUSER_CREATE': INFINITY_OBJUSER + '/create',
  'INFINITY_OBJUSER_DELETE': INFINITY_OBJUSER + '/delete',
  'INFINITY_OBJUSER_GET': INFINITY_OBJUSER + '/get',
  'INFINITY_OBJUSER_LIST': INFINITY_OBJUSER + '/list',

  //AD域
  'SMARTOR_ALLDOMAINUSERS_LIST': SMARTOR_AD_DOMAIN_IDENTIFY + '/user/listall',
  'SMARTOR_DOMAINGROUP_LIST': SMARTOR_AD_DOMAIN_IDENTIFY + '/group/list',
  'SMARTOR_DOMAINUSERBYGROUP_LIST': SMARTOR_AD_DOMAIN_IDENTIFY + '/user/listbygroup',
  'SMARTOR_DOMAININFO_LIST': SMARTOR_AD_DOMAIN_IDENTIFY + '/info',
  'SMARTOR_DOMAIN_LOGOUT': SMARTOR_AD_DOMAIN_IDENTIFY + '/leave',
  'SMARTOR_DOMAIN_JOIN': SMARTOR_AD_DOMAIN_IDENTIFY + '/join',
  'INFINITY_DOMAIN_LOGOUT': INFINITY_SERVER + '/system/aduser/leave',
  'INFINITY_DOMAIN_JOIN': INFINITY_SERVER + '/system/aduser/join',
  //FIXME
  'INFINITY_DOMAIN_CACHER': SMARTOR_SERVER + '/system/user/ad/user/cacher',

  //LDAP域
  'INFINITY_LDAP_DOMAIN_JOIN': SMARTOR_LDAP_DOMAIN_IDENTIFY + '/join',
  'INFINITY_LDAP_DOMAIN_LOGOUT': SMARTOR_LDAP_DOMAIN_IDENTIFY + '/leave',
  'INFINITY_LDAP_DOMAIN_SEARCH': SMARTOR_LDAP_DOMAIN_IDENTIFY + '/search',
  'INFINITY_LDAP_DOMAIN_INFO': SMARTOR_LDAP_DOMAIN_IDENTIFY + '/info',
  'INFINITY_LDAP_DOMAIN_LIST': SMARTOR_LDAP_DOMAIN_IDENTIFY + '/user/list',
  'INFINITY_LDAP_DOMAIN_LIST_BY_GROUP': SMARTOR_LDAP_DOMAIN_IDENTIFY + '/user/listbygroup',
  'INFINITY_LDAP_DOMAIN_CACHER': SMARTOR_LDAP_DOMAIN_IDENTIFY + '/user/cacher',
  'INFINITY_LDAP_DOMAIN_LIST_GROUP': SMARTOR_LDAP_DOMAIN_IDENTIFY + '/group/list',
  //用户组模块
  'SMARTOR_GROUP_LIST': SMARTOR_GROUP_IDENTIFY + '/list',
  'SMARTOR_GROUP_CREATE': SMARTOR_GROUP_IDENTIFY + '/create',
  'SMARTOR_GROUP_REMOVE': SMARTOR_GROUP_IDENTIFY + '/remove',
  //session
  'SESSION_CGI': IDENTIFY_CENTER_URL + '/session',
  'GET_SESSION': SESSION_CGI + '/get',
  'SET_SESSION': SESSION_CGI + '/set',
  'GET_VERSION': CLUSTER_TRACKER_URL+'/product/version/datrix',

  // infinity version
  // 节点模块
  'INFINITY_NODE_MGM': INFINITY_SERVER + '/cluster/system/node',
  'INFINITY_NODE_CHECK': INFINITY_NODE_MGM + '/check',
  'INFINITY_NODE_ADD': INFINITY_NODE_MGM+'/add',
  'INFINITY_NODE_LIST': INFINITY_NODE_MGM+'/list',
  'INFINITY_NODE_DEL': INFINITY_NODE_MGM+'/remove',
  'INFINITY_NODE_INIT': INFINITY_NODE_MGM+'/init',
  'INFINITY_STORAG_LIST': INFINITY_NODE_MGM+'/list',

  'INFINITY_NODE_SYSINFO': INFINITY_SERVER + '/system/info',// 系统信息
  'INFINITY_NODE_TIME': INFINITY_SERVER + '/system/time', //时钟
  'INFINITY_NODE_NET': INFINITY_SERVER + '/system/net', //网络
  'INFINITY_NODE_DISK': INFINITY_SERVER + '/system/disk', //磁盘
  'INFINITY_NODE_POWER': INFINITY_SERVER + '/system/power', //电源
  //系统信息
  'INFINITY_NODE_LISTBASIC': INFINITY_NODE_SYSINFO+'/sysinfo',
  'INFINITY_NODE_LISTRUNTIME': INFINITY_NODE_SYSINFO+'/runtime',
  'INFINITY_NODE_EDITHOSTNAME': INFINITY_NODE_SYSINFO+'/hostname/set',
  'INFINITY_SERVICES_LIST': INFINITY_SERVER+'/misc/dservices/list',
  'INFINITY_PLATFORM_RUN_STATE':INFINITY_SERVER+'/common/log/listbydate',
  'INFINITY_PLATFORM_LOAD_STATE':INFINITY_SERVER+'/cluster/nodes/status',
  'INFINITY_PLATFORM_STORAGE_INFO':INFINITY_SERVER+'/pool/usage',
  //时钟设置
  'INFINITY_NODE_SETNTPNAME': INFINITY_NODE_TIME + '/ntp/set',
  'INFINITY_NODE_GETNTPNAME': INFINITY_NODE_TIME + '/ntp/get',
  'INFINITY_NODE_LISTCLOCK': INFINITY_NODE_TIME + '/info',
  'INFINITY_NODE_LISTCITYS': INFINITY_NODE_TIME + '/citys',
  'INFINITY_CLOCK_SETTIME': INFINITY_NODE_TIME + '/set',
  'INFINITY_CLOCK_SETCITY': INFINITY_NODE_TIME + '/city/set',

  // mgr
  'INFINITY_NODE_MGR_GET': '/cluster/mgr/status',
  'INFINITY_NODE_MGR_ADD': '/cluster/mgr/add',
  'INFINITY_NODE_MGR_DELETE': '/cluster/mgr/remove',
  'INFINITY_NODE_MGR_START': '/cluster/mgr/start',
  'INFINITY_NODE_MGR_STOP': '/cluster/mgr/stop',

  //NTP
  'INFINITY_MISC_CLOCK': INFINITY_SERVER + '/misc/clock',
  'INFINITY_CLOCK_SERVICE_START': INFINITY_MISC_CLOCK+ '/service/init',
  'INFINITY_SET_CLOCK_SOURCE': INFINITY_MISC_CLOCK+ '/source/set',
  'INFINITY_GET_CLOCK_SOURCE': INFINITY_MISC_CLOCK + '/source/get',
  'INFINITY_SET_MASTERS': INFINITY_MISC_CLOCK+ '/master/set',
  'INFINITY_GET_MASTERS': INFINITY_MISC_CLOCK + '/master/get',
  'INFINITY_DEL_MASTERS': INFINITY_MISC_CLOCK+ '/master/remove',
  'INFINITY_ADJUST_CLOCK': INFINITY_MISC_CLOCK + '/node/adjust',
  'INFINITY_LIST_NODE_SOURCE': INFINITY_MISC_CLOCK + '/node/src/list',
  'INFINITY_GET_CHARACTER': INFINITY_MISC_CLOCK + '/node/character/get',
  'INFINITY_INIT_CLOCK': INFINITY_MISC_CLOCK+ '/node/init',

  //网络
  'INFINITY_NET_LISTBASIC': INFINITY_NODE_NET+'/info',
  '_NET_LISTBASIC':'/system/net/info',
  'INFINITY_NET_IPSET': INFINITY_NODE_NET+'/set',
  '_NET_IPSET':'/system/net/ethernet/set',
  '_NET_BONDIPSET':'/system/bond/set',
  'INFINITY_NET_BOND': INFINITY_NODE_NET+'/bond/set',
  'INFINITY_NET_DFGWDEV': INFINITY_NODE_NET+'/gateway/get',
  '_NET_DFGWDEV':'/system/net/gateway/get',
  'INFINITY_NET_DFGWDEVSET': INFINITY_NODE_NET+'/gateway/set',
  '_NET_DFGWDEVSET':'/system/net/gateway/set',
  'INFINITY_NET_RELEASE': INFINITY_NODE_NET+'/bond/unset',
  'INFINITY_NET_DNSSET': INFINITY_NODE_NET+'/dns/set',
  '_NET_DNSSET':'/system/net/dns/set',
  'INFINITY_NET_ETHINFO': INFINITY_NODE_NET + '/ethernet/info',
  '_NET_ETHINFO':'/system/net/ethernet/info',
'_NET_BOND': '/system/net/bond/set',
  '_NET_ADD_BOND_NIC': '/system/net/bond/add',
  '_NET_DEL_BOND_NIC': '/system/net/bond/delete',
  '_NET_PING': '/system/net/ping',
  '_NET_RELEASE': '/system/net/bond/unset',
  '_DELETE_MONITOR': '/misc/monitor/net/delete',
  '_SET_MONITOR': '/misc/monitor/net/set',

  //分区和磁盘
  'INFINITY_DISK_LIST': INFINITY_NODE_DISK+'/list',
  'INFINITY_DISK_LISTPART': INFINITY_NODE_DISK+'/part/info',
  'INFINITY_DISK_LISTPART_TOCREATE': INFINITY_NODE_DISK+'/part/info',
  'INFINITY_PART_DEL': INFINITY_NODE_DISK+'/part/delete',
  'INFINITY_PART_ADD': INFINITY_NODE_DISK+'/part/make',
  'INFINITY_PART_UNMOUNT': INFINITY_NODE_DISK+'/part/umount',
  #'INFINITY_PART_FORMAT': INFINITY_NODE_DISK+'/mkfspart', // 格式化分区
  'INFINITY_DISK_RESCAN': INFINITY_NODE_DISK+'/rescan',
  'INFINITY_CLEAN_CACHE': INFINITY_NODE_DISK+'/cache/clean',
  'INFINITY_REFRESH_CACHE': INFINITY_NODE_DISK+'/cache/refresh',
  'INFINITY_SET_LOCATION':'/system/disk/locate',

  'INFINITY_DISKMGM_LISTDETAILS': INFINITY_NODE_DISK+ '/classify',
  #'INFINITY_DISKMGM_LIST': INFINITY_NODE_DISK+ '/classify',
  #'INFINITY_DISKMGM_LISTDETAIL': INFINITY_NODE_DISK+ '/usage',

  //节点信息 关机与启动
  'INFINITY_POWER_REBOOT': INFINITY_NODE_POWER+ '/reboot',
  'INFINITY_POWER_SHUTDOWN': INFINITY_NODE_POWER+ '/down',

  // 基本信息模块
  // 许可证管理
  'SMARTOR_LICENSE_MGM': SMARTOR_SERVER + '/license' ,
  'SMARTOR_SERVER_MACHINENAME': SMARTOR_SERVER+'/system/info/serverinfo',
  'SMARTOR_ADD_REGCODE': SMARTOR_LICENSE_MGM +'/add',
  'SMARTOR_DEL_REGCODE': SMARTOR_LICENSE_MGM + '/delete',
  'SMARTOR_LIST_REGCODE': SMARTOR_LICENSE_MGM + '/list',
  'SMARTOR_ACTIVE_REGCODE': SMARTOR_LICENSE_MGM + '/activate',

  //文件共享
  'SMARTOR_AFP_CREATE': SMARTOR_STORAGE_AFP+'/create',
  'SMARTOR_AFP_DEL': SMARTOR_STORAGE_AFP+'/delete',
  'SMARTOR_AFP_LISTALL': SMARTOR_STORAGE_AFP+'/list/all',
  'SMARTOR_AFP_LIST': SMARTOR_STORAGE_AFP+'/list',

  'SMARTOR_FTP_CREATE': SMARTOR_STORAGE_FTP+'/create',
  'SMARTOR_FTP_DEL': SMARTOR_STORAGE_FTP+'/delete',
  'SMARTOR_FTP_LISTALL': SMARTOR_STORAGE_FTP+'/list/all',
  'SMARTOR_FTP_LIST': SMARTOR_STORAGE_FTP+'/list',

  'SMARTOR_HTTP_CREATE': SMARTOR_STORAGE_HTTP+'/create',
  'SMARTOR_HTTP_DEL': SMARTOR_STORAGE_HTTP+'/delete',
  'SMARTOR_HTTP_LISTALL': SMARTOR_STORAGE_HTTP+'/list/all',
  'SMARTOR_HTTP_LIST': SMARTOR_STORAGE_HTTP+'/list',

  'SMARTOR_NFS_CREATE':  SMARTOR_STORAGE_NFS+'/create',
  'SMARTOR_NFS_DEL': SMARTOR_STORAGE_NFS+'/delete',
  'SMARTOR_NFS_LISTALL': SMARTOR_STORAGE_NFS+'/list/all',
  'SMARTOR_NFS_LIST': SMARTOR_STORAGE_NFS+'/list',

  'SMARTOR_CIFS_CREATE': SMARTOR_STORAGE_CIFS+'/create',
  'SMARTOR_CIFS_DEL': SMARTOR_STORAGE_CIFS+'/delete',
  'SMARTOR_CIFS_LISTALL': SMARTOR_STORAGE_CIFS+'/list/all',
  'SMARTOR_CIFS_LIST': SMARTOR_STORAGE_CIFS+'/list',
  'INFINITY_MISC_SESSION_STATUS': INFINITY_SERVER + '/misc/cifs/session/status',

  //目录管理接口
  'SMARTOR_DIR_LIST': SMARTOR_STORAGE_DIR + '/list',
  'SMARTOR_DIR_CREATE': SMARTOR_STORAGE_DIR + '/create',
  'SMARTOR_DIR_DEL': SMARTOR_STORAGE_DIR + '/delete',
  'SMARTOR_DIR_LISTACL': SMARTOR_STORAGE_DIR + '/acl/list',
  'SMARTOR_DIR_SETOWNER': SMARTOR_STORAGE_DIR + '/owner/set',
  'SMARTOR_DIR_CLEAR': SMARTOR_STORAGE_DIR + '/acl/clear',
  'SMARTOR_DIRPRO_SET': SMARTOR_STORAGE_DIR + '/acl/set',
  'SMARTOR_DIRPRO_SEARCH': SMARTOR_STORAGE_DIR + '/search',
  //集群管理基本信息
  'INFINITY_CLUSTER_BASIC': INFINITY_SERVER + '/misc/sysdb',
  '_CLUSTER_BASIC': '/misc/sysdb',
  '_CLUSTER_BASIC_ADD': _CLUSTER_BASIC + '/add',
  '_CLUSTER_BASIC_DEL': _CLUSTER_BASIC + '/del',
  'INFINITY_CLUSTER_BASIC_INFO': INFINITY_CLUSTER_BASIC + '/info',
  'INFINITY_CLUSTER_HEALTH': INFINITY_CLUSTER_BASIC + '/health',
  //集群管理磁盘信息
  'INFINITY_IDISK': INFINITY_SERVER + '/cluster/idisk',
  'INFINITY_DISKMGM_DETAILBYTYPE': INFINITY_IDISK + '/detail',
  'INFINITY_DISKMGM_DETAIL': INFINITY_IDISK + '/detail',
  'INFINITY_DISK_ADDWIZARD': INFINITY_IDISK + '/add', # 配置向导
  #'INFINITY_DISKMGM_CREATE': INFINITY_IDISK+ '/add',
  'INFINITY_DISKMGM_DEL': INFINITY_IDISK + '/remove',
  'INFINITY_DISKMGM_ACTIVATE': INFINITY_IDISK + '/activate',

  'INFINITY_CLUSTER': INFINITY_SERVER + '/cluster',
  'INFINITY_CLUSTER_SHUTDOWN': INFINITY_CLUSTER + '/poweroff',
  'INFINITY_CLUSTER_SHUTDOWNPREWORK': INFINITY_CLUSTER + '/shutdown/prework',
  'INFINITY_CLUSTER_RECOVER': INFINITY_CLUSTER + '/recovery/ratio/get',
  //'INFINITY_CREATE_CLUSTER': INFINITY_CLUSTER+ '/create',
  'INFINITY_DELETE_CLUSTER': INFINITY_CLUSTER+ '/delete',
  'INFINITY_STATUS_HEALTH': INFINITY_CLUSTER+ '/health',
  //'INFINITY_STATUS_WARN': INFINITY_CLUSTER+ '/warn',
  // 'INFINITY_STATUS_OVERALL': INFINITY_CLUSTER+ '/node/status',
  'INFINITY_STATUS_OVERALL': INFINITY_CLUSTER+ '/system/node/summary',

  'INFINITY_MONITOR_SERVICE_ADD': INFINITY_CLUSTER+ '/monitor/add',
  'INFINITY_MONITOR_SERVICE_DEL': INFINITY_CLUSTER+ '/monitor/remove',
  'INFINITY_MONITOR_SERVICE_START': INFINITY_CLUSTER+ '/monitor/start',
  'INFINITY_MONITOR_SERVICE_STOP': INFINITY_CLUSTER+ '/monitor/stop',
  'INFINITY_MONITOR_LIST': INFINITY_CLUSTER+ '/monitor/status',
  'INFINITY_CREATE_CLUSTER': INFINITY_CLUSTER+ '/monitor/create',

  'INFINITY_STORAG_STATE': INFINITY_CLUSTER+ '/storage/state',
  'INFINITY_STORAG_DESTROY': INFINITY_CLUSTER+ '/storage/destroy',
  'INFINITY_STORAG_ADDNODE': INFINITY_CLUSTER+ '/storage/node/add',
  'INFINITY_STORAG_DELNODE': INFINITY_CLUSTER+ '/storage/node/remove',
  'INFINITY_STORAG_STOPNODE': INFINITY_CLUSTER+ '/storage/node/stop',
  'INFINITY_STORAG_STARTNODE': INFINITY_CLUSTER+ '/storage/node/start',
  'INFINITY_STORAGNODE_LIST': INFINITY_CLUSTER+ '/storage/node/list' ,
  'INFINITY_STORAGENODE_LIST': INFINITY_CLUSTER+ '/storage/node/status',

  'INFINITY_METADATA_SERVICE_ADD': INFINITY_CLUSTER+ '/mds/add',
  'INFINITY_METADATA_SERVICE_DEL': INFINITY_CLUSTER+ '/mds/remove',
  'INFINITY_METADATA_SERVICE_START': INFINITY_CLUSTER+ '/mds/start',
  'INFINITY_METADATA_SERVICE_STOP': INFINITY_CLUSTER+ '/mds/stop',
  'INFINITY_METASERVER_LIST': INFINITY_CLUSTER+ '/mds/status',

  'INFINITY_OBJSTORAGE_SERVICE_ADD': INFINITY_CLUSTER+ '/oss/add',
  'INFINITY_OBJSTORAGE_SERVICE_DEL': INFINITY_CLUSTER+ '/oss/remove',
  'INFINITY_OBJSTORAGE_SERVICE_START': INFINITY_CLUSTER+ '/oss/start',
  'INFINITY_OBJSTORAGE_SERVICE_STOP': INFINITY_CLUSTER+ '/oss/stop',
  'INFINITY_OBJSERVER_LIST': INFINITY_CLUSTER+ '/oss/status',

  //维护
  'INFINITY_MAINTAINSTAT_GET': INFINITY_CLUSTER + '/maintain/status',
  'INFINITY_MAINTAINSTAT_SET': INFINITY_CLUSTER + '/maintain/set',

  //存储池
  'INFINITY_POOL_MGM': INFINITY_SERVER + '/pool',
  'INFINITY_STORAGEPOOL_LIST': INFINITY_POOL_MGM + '/info',

  'INFINITY_STORAGEPOOL_ADD': INFINITY_POOL_MGM + '/create',
  'INFINITY_STORAGEPOOL_DEL': INFINITY_POOL_MGM + '/delete',
  'INFINITY_STORAGEPOOL_DISKS': INFINITY_POOL_MGM + '/disk/avail',
  'INFINITY_STORAGEPOOL_UPDATEDISKS':  INFINITY_POOL_MGM + '/disk/update',
  'INFINITY_STORAGEPOOL_POOLS': INFINITY_POOL_MGM + '/list',
  'INFINITY_LIST_POOLS': INFINITY_POOL_MGM + '/list',
  'INFINITY_LIST_POOLS_APPLICATION': INFINITY_POOL_MGM + '/application/list',
  'INFINITY_STATIS_LIST': INFINITY_POOL_MGM + '/perf',
  'INFINITY_STATIS_HISTORY': INFINITY_POOL_MGM + '/stats/get',
  'INFINITY_POOL_USEDSPACE': INFINITY_POOL_MGM + '/df',
  'INFINITY_POOL_QUOTAGET': INFINITY_POOL_MGM + '/quota/get',
  'INFINITY_POOL_QUOTASET': INFINITY_POOL_MGM + '/quota/set',

  //文件系统
  'INFINITY_FILESYS_BASIC': INFINITY_SERVER + '/filesystem',
  'INFINITY_FILESYS_LIST': INFINITY_FILESYS_BASIC + '/info',
  'INFINITY_FILESYS_CREATE': INFINITY_FILESYS_BASIC + '/create',
  'INFINITY_FILESYS_DELETE': INFINITY_FILESYS_BASIC + '/delete',
  'INFINITY_FILESYS_EDITAVAIL': INFINITY_FILESYS_BASIC + '/modify_avail_cap',
  'SMARTOR_MOUNTPOINT_LIST': INFINITY_FILESYS_BASIC + '/mountpoint',
  'INFINITY_MOUNTPOINT_MOUNT':  INFINITY_FILESYS_BASIC + '/mount',
  'INFINITY_MOUNTPOINT_UMOUNT':  INFINITY_FILESYS_BASIC + '/umount',
  'INFINITY_MOUNTNODE_MOUNT':  INFINITY_FILESYS_BASIC + '/nodemount',
  'INFINITY_MOUNTNODE_UMOUNT':  INFINITY_FILESYS_BASIC + '/nodeumount',
  'INFINITY_MOUNTNODE_LIST':  INFINITY_FILESYS_BASIC + '/nodeismounted',
  'INFINITY_QUOTA_GET': INFINITY_FILESYS_BASIC + '/quota/dir/get',
  'INFINITY_QUOTA_SET': INFINITY_FILESYS_BASIC + '/quota/dir/set',
  'INFINITY_QUOTA_FILEGET': INFINITY_FILESYS_BASIC + '/quota/dir/files/get',
  'INFINITY_QUOTA_FILESET': INFINITY_FILESYS_BASIC + '/quota/dir/files/set',

  //对象存储管理
  'INFINITY_OBJSYS': INFINITY_SERVER + '/os',
  'INFINITY_OBJSYS_LIST': INFINITY_OBJSYS + '/pool/get',
  'INFINITY_OBJSYS_CREATE': INFINITY_OBJSYS + '/pool/set',

  //卷管理
  'INFINITY_VOLUME_MGM': INFINITY_SERVER + '/volume',
  'INFINITY_SNAPSHOT_ACT': INFINITY_VOLUME_MGM + '/snapshot',

  'INFINITY_VOLUME_CREATE': INFINITY_VOLUME_MGM + '/image/create',
  'INFINITY_VOLUME_DEL': INFINITY_VOLUME_MGM + '/image/delete',
  'INFINITY_VOLUME_LIST': INFINITY_VOLUME_MGM + '/image/list',
  'INFINITY_VOLUME_LISTALL': INFINITY_VOLUME_MGM + '/info',
  'INFINITY_VOLUME_EDIT': INFINITY_VOLUME_MGM + '/image/update',
  'INFINITY_SNAPSHOT_CREATE': INFINITY_SNAPSHOT_ACT + '/create',
  'INFINITY_SNAPSHOT_DEL': INFINITY_SNAPSHOT_ACT + '/delete',
  'INFINITY_CLONE_CREATE': INFINITY_VOLUME_MGM + '/image/clone',

  // 操作日志
  'INFINITY_SERVER_LOG': INFINITY_SERVER + '/common/log/list' ,
  'INFINITY_EXPORT_LOGS':INFINITY_SERVER + '/system/export/get',
  'INFINITY_CLEAR_LOGS':INFINITY_SERVER + '/system/export/clear',
  //'INFINITY_SERVER_ALARM': INFINITY_SERVER + '/misc/monitor/list',
  'INFINITY_SERVER_ALARM': INFINITY_SERVER + '/cluster/summary',
  'INFINITY_ALARMCONF_SET': INFINITY_SERVER + '/misc/monitor/set',
  'INFINITY_ALARMCONF_GET': INFINITY_SERVER + '/misc/monitor/get',
  'INFINITY_ALARM_RECORDS_LIST': INFINITY_SERVER + '/misc/monitor/list',
  'INFINITY_AUDITLOG_LIST': INFINITY_SERVER + '/misc/audit/log/list',
  'INFINITY_AUDITLOG_SEARCH': INFINITY_SERVER + '/misc/audit/log/search',
  'INFINITY_AUDITLOG_CLEAR': INFINITY_SERVER + '/misc/audit/log/clear',

  //配置向导 公共IP smartor的
  'SMARTOR_STORAGE_CNAS': SMARTOR_SERVER + '/storage/cnas',
  'SMARTOR_CNAS_PUBADDR': SMARTOR_STORAGE_CNAS + '/pubaddr',
  'INFINITY_PUBIP_LIST': SMARTOR_CNAS_PUBADDR + '/list',
  'INFINITY_PUBIP_ADD': SMARTOR_CNAS_PUBADDR + '/add',
  'INFINITY_PUBIP_MODIFY': SMARTOR_CNAS_PUBADDR + '/modify',
  'INFINITY_PUBIP_DEL': SMARTOR_CNAS_PUBADDR + '/delete',
  'INFINITY_PUBIP_RESET': SMARTOR_CNAS_PUBADDR + '/reset',
  'INFINITY_BEFORE_CREATESHARE': SMARTOR_STORAGE_CNAS + '/role/set',
  'INFINITY_BEFORE_JOINDOMAIN': SMARTOR_STORAGE_CNAS + '/role/get',

  //NAS
  'INFINITY_CNAS_NODE': SMARTOR_STORAGE_CNAS + '/node',
  'INFINITY_NAS_SERVICE_ADD': INFINITY_CNAS_NODE + '/add',
  'INFINITY_NAS_SERVICE_DEL': INFINITY_CNAS_NODE + '/remove',
  'INFINITY_NAS_SERVICE_START': INFINITY_CNAS_NODE + '/start',
  'INFINITY_NAS_SERVICE_STOP': INFINITY_CNAS_NODE + '/stop',
  'INFINITY_NAS_LIST': INFINITY_CNAS_NODE + '/list',
  'INFINITY_ALL_NAS_SERVICE_STOP': SMARTOR_STORAGE_CNAS + '/service/stopservices',
  'INFINITY_ALL_NAS_SERVICE_START': SMARTOR_STORAGE_CNAS + '/service/startservices',

  //配置向导  DNS
  'INFINITY_SYS_DNS': INFINITY_SERVER + '/system/dns',
  'INFINITY_DNS_LIST': INFINITY_SYS_DNS + '/info',
  'INFINITY_DNS_ON': INFINITY_SYS_DNS + '/start',
  'INFINITY_DNS_OFF': INFINITY_SYS_DNS + '/stop',
  'INFINITY_DNS_MASTER': INFINITY_SYS_DNS + '/set_master',
  'INFINITY_DNS_SECOND':  INFINITY_SYS_DNS + '/set_slave',
  'INFINITY_DNSSER_SET': INFINITY_SYS_DNS + '/set',
  'INFINITY_DNS_LISTNODE': INFINITY_SYS_DNS + '/list',

  'INFINITY_MISC_MONITORZONE': INFINITY_SERVER + '/misc/dns/monitorzone',
  'INFINITY_MISC_DNS': INFINITY_SERVER + '/misc/dns',
  'INFINITY_DNS_NODE': INFINITY_MISC_DNS + '/node',
  'INFINITY_DNS_ZONE': INFINITY_MISC_DNS + '/zone',
  'INFINITY_GET_FORWARDER':INFINITY_MISC_DNS + '/forwarder/get',
  'INFINITY_SET_FORWARDER':INFINITY_MISC_DNS + '/forwarder/set',

  'INFINITY_MONITORZONE_CREATE': INFINITY_MISC_MONITORZONE + '/create',
  'INFINITY_MONITORZONE_QUERY': INFINITY_MISC_MONITORZONE + '/query',
  'INFINITY_DNS_NODE_ADD': INFINITY_DNS_NODE + '/add',
  'INFINITY_DNS_NODE_DEL': INFINITY_DNS_NODE + '/del',
  'INFINITY_DNS_ZONE_QUERY': INFINITY_DNS_ZONE + '/query',
  'INFINITY_DNS_ZONE_ADD': INFINITY_DNS_ZONE + '/add',
  'INFINITY_DNS_ZONE_DEL': INFINITY_DNS_ZONE + '/del',

  //服务列表
  'INFINITY_MISC_DSERVICES': INFINITY_SERVER + '/misc/dservices',
  'INFINITY_DSERVICES_LIST': INFINITY_MISC_DSERVICES + '/list',
  'INFINITY_DSERVICES_START': INFINITY_MISC_DSERVICES + '/start',
  'INFINITY_DSERVICES_RGW_START': INFINITY_SERVER + '/cluster/rgw/start',
  'INFINITY_DSERVICES_STOP': INFINITY_MISC_DSERVICES + '/stop',
  'INFINITY_DSERVICES_RGW_STOP': INFINITY_SERVER + '/cluster/rgw/start',

  //NAS和公共IP整合之后的NAS API
   'INFINITY_NAS_PUBLICIP': SMARTOR_SERVER + '/storage/cnas/nodepubaddr' ,
   'INFINITY_NASPUBIP_LIST': INFINITY_NAS_PUBLICIP + '/list' ,
   'INFINITY_NASPUBIP_DEL': INFINITY_NAS_PUBLICIP + '/remove' ,
   'INFINITY_NASPUBIP_ADD': INFINITY_NAS_PUBLICIP + '/reset' ,

  //SNMP配置接口
  'SMARTOR_SYS_ALARM': SMARTOR_SERVER + '/system/alarm',
  'SMARTOR_ALARM_SNMP': SMARTOR_SYS_ALARM + '/snmp',
  'SMARTOR_EMAIL_ACT': SMARTOR_SYS_ALARM + '/email',
  //SMTP配置接口
  'INFINITY_SMTP_CONF': SMARTOR_SYS_ALARM + '/smtpconf',
  'INFINITY_ALARM_STATUS': SMARTOR_SYS_ALARM + '/alarmconf',
  'INFINITY_SMTP_SENDTESTEMAIL': SMARTOR_SYS_ALARM + '/smtpconf/test',
  'INFINITY_EMAIL_SETSTATUS': SMARTOR_EMAIL_ACT + '/set',
  'INFINITY_EMAIL_ADD': SMARTOR_EMAIL_ACT + '/addr/add',
  'INFINITY_EMAIL_DEL': SMARTOR_EMAIL_ACT + '/addr/delete',
  'INFINITY_SMTPCONF_SET': INFINITY_SMTP_CONF + '/set',

  'INFINITY_SNMP_GET': SMARTOR_ALARM_SNMP + '/get',
  'INFINITY_SNMP_SET': SMARTOR_ALARM_SNMP + '/set',
  'INFINITY_SNMP_TEST': SMARTOR_ALARM_SNMP + '/test',

  //初始化
  'INFINITY_SERVER_INIT': SMARTOR_SERVER + '/system/conf/env/init',

  //版本
  'INFINITY_VERSION_GET': INFINITY_SERVER + '/version',

  // infinity permission+ 定义的字段需要和controller模块相对应
  'PERMISSION_WEB_ALL': 'all',
  'PERMISSION_WEB_HOME': 'sthome',
  'PERMISSION_WEB_SYSMAG': 'sysmanage',
  'PERMISSION_WEB_CLUSTERMAG': 'clustermang',
  'PERMISSION_WEB_STORAGEMAG': 'storagemgm',
  'PERMISSION_WEB_SYSSERVER': 'sysserver',

  //磁盘管理INFINITY_SERVER
  'INFINITY_SERVER_PROGRESS': INFINITY_SERVER + '/task/idisk/add/progress',

  //系统重置
  '_CONF_RESET': '/api/system/conf/reset',
  '_CLUSTER_RESET': '/api/infinity-v2/cluster/system/reset',
  '_CONF_RESET_ADMIN': '/api/system/conf/reset/admin',
  '_SYSDB_RESET': '/api/infinity-v2/misc/sysdb/reset',
  '_IDISK_RESET': '/api/infinity-v2/cluster/idisk/reset',

};

module.exports = patterns;
